name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Release apk and aab
        run: ./gradlew assembleRelease bundleRelease --stacktrace

      - name: Find APK and AAB files
        id: find_files
        run: |
          APK_PATH=$(find . -name "app-release-unsigned.apk" | head -n 1)
          AAB_PATH=$(find . -name "app-release-unsigned.aab" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ${{ env.APK_PATH }}

      - name: Upload AAB to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: ${{ env.AAB_PATH }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Unit Tests
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Download app bundle
      - name: Download app bundle from artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release.aab
          path: ./

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: fr.thomasbernard03.tarot
          releaseFiles: ${{ github.workspace }}/app-release-unsigned.aab
          track: production